/**
 * The scaffold board's link table, for the wiring guide.
 *
 * WHAT THIS EXISTS TO CLOSE. A fitted link on the scaffold board stands in for an
 * absent section; a removed one lets the real section board drive that segment. Get
 * that backwards on one leg of a two-leg stand-in and the mistake is quiet and
 * plausible: 0.589 dB of spurious load that reads as a measurement, not a wiring
 * error (`docs/superpowers/specs/2026-10-09-pultec-section-scaffold-design.md`,
 * "Isolation"). The guide exists so a builder reads which links go with which
 * section, rather than reconstructing it from a bag of unlabelled jumpers.
 *
 * RECOVERED FROM THE MODEL AND THE NETWORK, NEVER FROM A LINK'S OWN ID. A link's id
 * (`link_low_boost_r2_a`, say) is generated by `circuits/pultec/scaffold.ts` and that
 * generator is private - `linkId`/`stubNet` are not exported, and parsing an id string
 * to recover which section it belongs to would be brittle even if they were. Instead,
 * each `StandIn`'s `IsolationPoint` already names the (component, terminal, net)
 * triple it isolates; the SAME component id appears unchanged on the scaffold board, so
 * reading that component's current pin there gives the stub net the isolation
 * introduced, and the one link joining that stub to the point's real net is the link
 * for that point - connectivity, not string matching.
 */
import type { Component, Network } from "../../model/types.ts"
import type { FlatState, IsolationPoint, StandIn } from "./index.ts"

/** The net on one of a component's terminals, package pins and unit pins both
 * checked - mirrors `pinsOf`/`netOf` in `../wiring.ts`, kept local rather than shared
 * so this module does not depend on that one's internals. */
function pinNet(component: Component, terminal: string): string | undefined {
  const packageConnection = component.pins[terminal]
  if (packageConnection !== undefined) {
    return packageConnection.kind === "net" ? packageConnection.net : undefined
  }
  for (const unit of component.units) {
    const connection = unit.pins[terminal]
    if (connection === undefined) continue
    return connection.kind === "net" ? connection.net : undefined
  }
  return undefined
}

/** A removable link, as `circuits/pultec/scaffold.ts`'s `toLinkComponent` emits it:
 * a two-position switch whose "fitted" position shorts pins "1" and "2". */
function isLink(component: Component): boolean {
  if (component.kind !== "switch") return false
  const positions = Reflect.get(component.parameters, "positions")
  return Array.isArray(positions) && positions.length === 2 &&
    positions[0] === "fitted" && positions[1] === "removed"
}

/** One link, resolved to the section it stands in for and the leg it breaks. */
export interface ScaffoldLinkEntry {
  readonly link: string
  readonly section: string
  readonly component: string
  readonly terminal: string
  readonly net: string
}

/**
 * Every scaffold link, matched to its owning section and isolation point by
 * connectivity against `network` - see the module comment for why that is the
 * recovery method rather than the link's own id.
 *
 * Throws rather than guessing when a point names a component or pin the network does
 * not have, or when a point's stub does not resolve to exactly one link: either means
 * `lib/board/scaffold/isolate.ts` and `circuits/pultec/scaffold.ts` have drifted apart,
 * and a guide built on a guess here would be confidently wrong.
 */
export function scaffoldLinkEntries(
  standIns: Readonly<Record<string, StandIn>>,
  network: Network,
): readonly ScaffoldLinkEntry[] {
  const byId = new Map(network.components.map((component) => [component.id, component]))
  const links = network.components.filter(isLink)
  const entries: ScaffoldLinkEntry[] = []

  for (const section of Object.keys(standIns).sort()) {
    const standIn = standIns[section]!
    for (const point of standIn.isolation) {
      entries.push(resolveLink(section, point, byId, links))
    }
  }
  return entries
}

function resolveLink(
  section: string,
  point: IsolationPoint,
  byId: ReadonlyMap<string, Component>,
  links: readonly Component[],
): ScaffoldLinkEntry {
  const component = byId.get(point.component)
  if (component === undefined) {
    throw new Error(
      `Scaffold wiring guide: the stand-in for "${section}" names an isolation point on ` +
        `"${point.component}", but no component with that id is on the scaffold board. ` +
        "lib/board/scaffold/isolate.ts and circuits/pultec/scaffold.ts have drifted apart.",
    )
  }
  const stub = pinNet(component, point.terminal)
  if (stub === undefined) {
    throw new Error(
      `Scaffold wiring guide: "${point.component}" has no net on terminal "${point.terminal}" on ` +
        `the scaffold board, but the stand-in for "${section}" names an isolation point there.`,
    )
  }
  const matches = links.filter((link) => pinNet(link, "1") === stub && pinNet(link, "2") === point.net)
  if (matches.length !== 1) {
    throw new Error(
      `Scaffold wiring guide: expected exactly one link joining "${stub}" to "${point.net}" for ` +
        `"${section}"'s isolation point on ${point.component}.${point.terminal}, found ${matches.length}.`,
    )
  }
  return { link: matches[0]!.id, section, component: point.component, terminal: point.terminal, net: point.net }
}

/**
 * The scaffold section of the wiring guide: the emulated setting, then every link
 * with the section it stands in for and the leg it breaks.
 *
 * Both halves of a two-link stand-in (low-boost, mid) carry the same section name
 * because they come from the same `StandIn` - there is no separate accounting that
 * could let them drift apart and read as two different, half-complete sections.
 */
export function scaffoldLinksSection(
  standIns: Readonly<Record<string, StandIn>>,
  flat: FlatState,
  network: Network,
  designators: Readonly<Record<string, string>>,
): string {
  const entries = scaffoldLinkEntries(standIns, network)
  const rows = entries.map((entry) => {
    const link = designators[entry.link] ?? entry.link
    return `| ${link} | ${entry.section} | ${entry.component} \`${entry.terminal}\` leg ↔ \`${entry.net}\` |`
  })
  return [
    "## Scaffold links",
    "",
    "This board carries one stand-in for every Pultec section that is not being built, so",
    "whichever subset of the five you have on the bench still sees a complete signal ladder.",
    "Each stand-in is taken out of circuit by one or two removable links:",
    "",
    "- **Fit** a section's link(s) when that section is **absent** - the stand-in then",
    "  carries the segment in its place.",
    "- **Remove** a section's link(s) when that section's own board is present - the",
    "  stand-in is left hanging by one point and carries nothing.",
    "",
    "Where a section needs two links, fit or remove BOTH together. One fitted and one",
    "removed is not a valid state for either section: it leaves the stand-in half",
    "connected, loading the ladder it should either carry whole or not touch at all.",
    "",
    `**Emulated setting.** The stand-ins assume low frequency ${flat.loFrequency}, high`,
    `frequency ${flat.hiFrequency}, mid frequency ${flat.midFrequency} in ${flat.midMode} mode.`,
    "That match only holds while every PRESENT section sharing a frequency control with an",
    "absent one is also set there - `lo_freq` gangs low-cut and low-boost together, so if",
    "one of them is absent, turning the other's frequency knob away from this setting",
    "invalidates every link standing in for the one that is missing.",
    "",
    "| Link | Stands in for | Breaks |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ].join("\n")
}
