/**
 * The scaffold board's link table, for the wiring guide.
 *
 * WHAT THIS EXISTS TO CLOSE. A fitted link on the scaffold board stands in for an
 * absent section; a removed one lets the real section board drive that segment. Get
 * that backwards on one leg of a two-leg stand-in and the mistake is quiet and
 * plausible: 0.589 dB of spurious load that reads as a measurement, not a wiring
 * error (`docs/superpowers/specs/2026-10-09-pultec-section-scaffold-design.md`,
 * "Isolation"). The guide exists so a builder reads which links go with which
 * section, rather than reconstructing it from a bag of unlabelled jumpers.
 *
 * RECOVERED FROM THE MODEL AND THE NETWORK, NEVER FROM A LINK'S OWN ID. A link's id
 * (`link_low_boost_r2_a`, say) is generated by `circuits/pultec/scaffold.ts` and that
 * generator is private - `linkId`/`stubNet` are not exported, and parsing an id string
 * to recover which section it belongs to would be brittle even if they were. Instead,
 * this module re-derives each stand-in's isolation legs itself - the same (component,
 * terminal, net) triple a leg isolates - from the `StandIn`'s own `components` and
 * `boundary`; the SAME component id appears unchanged on the scaffold board, so
 * reading that component's current pin there gives the stub net the isolation
 * introduced, and the one link joining that stub to the leg's real net is the link
 * for that leg - connectivity, not string matching.
 *
 * `legsFor` BELOW IS A TEMPORARY, PRIVATE DUPLICATE of the leg-finding algorithm that
 * used to live in `lib/board/scaffold/isolate.ts` (deleted - see "Task 2: Retire
 * isolation"). `StandIn` no longer carries isolation data, because the owner's
 * build-time-population model has no further use for it; **Task 6, "Population and
 * junction instructions in the guide"** rewrites this file wholesale and removes this
 * copy with it. `circuits/pultec/scaffold.ts` carried the other, identical copy;
 * **Task 4, "Delete the separate scaffold board"** removed it outright - not
 * redesigned - by deleting that whole file, so this is now the sole surviving copy,
 * and it survives only until Task 6's rewrite removes it too. The computation stays
 * local rather than being reinstated as shared machinery in `lib/`.
 *
 * NO BOARD IS DECLARED FOR THE SCAFFOLD YET. `boards/<name>/perfboard.json` hands a
 * board to the perfboard CLI, and that contract needs a physicalization - a
 * `DESIGNATORS` map, pad orders, an off-board set - the same way `circuits/pultec/
 * physical/hi-boost.ts` and its four siblings supply one for each section board. No
 * such module exists for the scaffold board. It cannot be added by exporting
 * `DESIGNATORS` directly from `circuits/pultec/scaffold.ts` either: every other
 * Pultec board's designators are facts about the vendored KiCad schematic (`CLAUDE.md`
 * - "a designator is a fact about one particular schematic"), and the scaffold board
 * has no schematic to be a fact about. Inventing `JP1..JP7` for the links would be
 * fabrication, not derivation. This module's `scaffoldLinkEntries`/`scaffoldLinksSection`
 * are verified directly against the real `pultecScaffold()` network instead - that
 * does not need a declared board - and a `perfboard.json` follows once the
 * physicalization exists to back it.
 */
import { connectedGroups } from "./shorts.ts"
import { GROUND_NET } from "./index.ts"
import type { Component, Network } from "../../model/types.ts"
import type { ResolvedComponent } from "../../model/control-state.ts"
import type { FlatState, StandIn } from "./index.ts"

/** A leg of a stand-in that must be breakable, named by the component and pin at it.
 * See the module comment for why this is a private duplicate rather than a shared
 * import. */
interface IsolationLeg {
  readonly component: string
  readonly terminal: string
  readonly net: string
}

/** Every (component, pin) sitting on a boundary net, one entry per distinct net. */
function externalTerminals(
  group: readonly ResolvedComponent[],
  boundary: ReadonlySet<string>,
): readonly IsolationLeg[] {
  const terminals: IsolationLeg[] = []
  const claimed = new Set<string>()
  for (const component of group) {
    for (const unit of component.units) {
      for (const [terminal, net] of Object.entries(unit.pins)) {
        if (!boundary.has(net) || claimed.has(net)) continue
        claimed.add(net)
        terminals.push({ component: component.id, terminal, net })
      }
    }
  }
  return terminals
}

/** For each connected piece of a stand-in, every external terminal but one - ground,
 * when the piece reaches it, is the one left. See `circuits/pultec/scaffold.ts`'s
 * identical `legsFor` for the fuller derivation; both copies must change together
 * until the later rewrite removes them. */
function legsFor(
  components: readonly ResolvedComponent[],
  boundary: ReadonlySet<string>,
  groundNet = GROUND_NET,
): readonly IsolationLeg[] {
  const legs: IsolationLeg[] = []
  for (const group of connectedGroups(components)) {
    const terminals = externalTerminals(group, boundary)
    const ordered = [...terminals].sort((a, b) => {
      if (a.net === groundNet) return 1
      if (b.net === groundNet) return -1
      return a.net < b.net ? -1 : a.net > b.net ? 1 : 0
    })
    legs.push(...ordered.slice(0, Math.max(ordered.length - 1, 0)))
  }
  return legs
}

/** The net on one of a component's terminals, package pins and unit pins both
 * checked - mirrors `pinsOf`/`netOf` in `../wiring.ts`, kept local rather than shared
 * so this module does not depend on that one's internals. */
function pinNet(component: Component, terminal: string): string | undefined {
  const packageConnection = component.pins[terminal]
  if (packageConnection !== undefined) {
    return packageConnection.kind === "net" ? packageConnection.net : undefined
  }
  for (const unit of component.units) {
    const connection = unit.pins[terminal]
    if (connection === undefined) continue
    return connection.kind === "net" ? connection.net : undefined
  }
  return undefined
}

/** A removable link, as `circuits/pultec/scaffold.ts`'s `toLinkComponent` emits it:
 * a two-position switch whose "fitted" position shorts pins "1" and "2". */
function isLink(component: Component): boolean {
  if (component.kind !== "switch") return false
  const positions = Reflect.get(component.parameters, "positions")
  return Array.isArray(positions) && positions.length === 2 &&
    positions[0] === "fitted" && positions[1] === "removed"
}

/** One link, resolved to the section it stands in for and the leg it breaks. */
export interface ScaffoldLinkEntry {
  readonly link: string
  readonly section: string
  readonly component: string
  readonly terminal: string
  readonly net: string
}

/**
 * Every scaffold link, matched to its owning section and isolation point by
 * connectivity against `network` - see the module comment for why that is the
 * recovery method rather than the link's own id.
 *
 * Throws rather than guessing when a leg names a component or pin the network does
 * not have, or when a leg's stub does not resolve to exactly one link: either means
 * this module's `legsFor` and `circuits/pultec/scaffold.ts`'s identical copy have
 * drifted apart, and a guide built on a guess here would be confidently wrong.
 */
export function scaffoldLinkEntries(
  standIns: Readonly<Record<string, StandIn>>,
  network: Network,
): readonly ScaffoldLinkEntry[] {
  const byId = new Map(network.components.map((component) => [component.id, component]))
  const links = network.components.filter(isLink)
  const entries: ScaffoldLinkEntry[] = []

  for (const section of Object.keys(standIns).sort()) {
    const standIn = standIns[section]!
    const legs = legsFor(standIn.components, new Set(standIn.boundary))
    for (const leg of legs) {
      entries.push(resolveLink(section, leg, byId, links))
    }
  }
  return entries
}

function resolveLink(
  section: string,
  leg: IsolationLeg,
  byId: ReadonlyMap<string, Component>,
  links: readonly Component[],
): ScaffoldLinkEntry {
  const component = byId.get(leg.component)
  if (component === undefined) {
    throw new Error(
      `Scaffold wiring guide: the stand-in for "${section}" names an isolation leg on ` +
        `"${leg.component}", but no component with that id is on the scaffold board. ` +
        "This module's legsFor and circuits/pultec/scaffold.ts's identical copy have drifted apart.",
    )
  }
  const stub = pinNet(component, leg.terminal)
  if (stub === undefined) {
    throw new Error(
      `Scaffold wiring guide: "${leg.component}" has no net on terminal "${leg.terminal}" on ` +
        `the scaffold board, but the stand-in for "${section}" names an isolation leg there.`,
    )
  }
  const matches = links.filter((link) => pinNet(link, "1") === stub && pinNet(link, "2") === leg.net)
  if (matches.length !== 1) {
    throw new Error(
      `Scaffold wiring guide: expected exactly one link joining "${stub}" to "${leg.net}" for ` +
        `"${section}"'s isolation leg on ${leg.component}.${leg.terminal}, found ${matches.length}.`,
    )
  }
  return { link: matches[0]!.id, section, component: leg.component, terminal: leg.terminal, net: leg.net }
}

/**
 * The scaffold section of the wiring guide: the emulated setting, then every link
 * with the section it stands in for and the leg it breaks.
 *
 * Both halves of a two-link stand-in (low-boost, mid) carry the same section name
 * because they come from the same `StandIn` - there is no separate accounting that
 * could let them drift apart and read as two different, half-complete sections.
 */
export function scaffoldLinksSection(
  standIns: Readonly<Record<string, StandIn>>,
  flat: FlatState,
  network: Network,
  designators: Readonly<Record<string, string>>,
): string {
  const entries = scaffoldLinkEntries(standIns, network)
  const rows = entries.map((entry) => {
    const link = designators[entry.link] ?? entry.link
    return `| ${link} | ${entry.section} | ${entry.component} \`${entry.terminal}\` leg ↔ \`${entry.net}\` |`
  })
  return [
    "## Scaffold links",
    "",
    "This board carries one stand-in for every Pultec section that is not being built, so",
    "whichever subset of the five you have on the bench still sees a complete signal ladder.",
    "Each stand-in is taken out of circuit by one or two removable links:",
    "",
    "- **Fit** a section's link(s) when that section is **absent** - the stand-in then",
    "  carries the segment in its place.",
    "- **Remove** a section's link(s) when that section's own board is present - the",
    "  stand-in is left hanging by one point and carries nothing.",
    "",
    "Where a section needs two links, fit or remove BOTH together. One fitted and one",
    "removed is not a valid state for either section: it leaves the stand-in half",
    "connected, loading the ladder it should either carry whole or not touch at all.",
    "",
    `**Emulated setting.** The stand-ins assume low frequency ${flat.loFrequency}, high`,
    `frequency ${flat.hiFrequency}, mid frequency ${flat.midFrequency} in ${flat.midMode} mode.`,
    "That match only holds while every PRESENT section sharing a frequency control with an",
    "absent one is also set there - `lo_freq` gangs low-cut and low-boost together, so if",
    "one of them is absent, turning the other's frequency knob away from this setting",
    "invalidates every link standing in for the one that is missing.",
    "",
    "| Link | Stands in for | Breaks |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ].join("\n")
}
